In [1]:
#Mini Project

In [2]:
#Mini Project
import numpy as np
age = np.array([5,6,7,8])
education_num = np.array([8,9,4,0])
race = np.array(["Amer-India_Eskimo","Asian", "Black", "White","Other"])
gender = np.array(["Male","Female"])
#Cap-gain = np.array()

data_file ='/content/drive/MyDrive/DetaSet/makeSenseOfCensus.csv'
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
print("\nData: \n\n", data)
print("\nType of data: \n\n", type(data))


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>


#Step 2 Append the data



In [3]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

new_data = np.concatenate((data,new_record))
print(new_data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


#Step 3 CHeck if it's a young country or old country


In [4]:
import numpy as np
age = new_data[:,0]
max_age = age.max()
print(max_age)
min_age = age.min()
print(min_age)
age_mean = age.mean()
print(age_mean)
age_std = age.std()
print(age_std)

90.0
17.0
38.06293706293706
13.341478176165857


#Step 4 Let's check the country's race distribution to identify the minorities


In [5]:
race = new_data[:,2]
print(np.unique(race))
race_0 = race[race == 0]
race_1 = race[race == 1]
race_2 = race[race == 2]
race_3 = race[race == 3]
race_4= race[race == 4]


print(race_0)
print(race_1)
print(race_2)
print(race_3)
print(race_4)

print(len(race))




[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.


In [6]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

print(len_0, len_1, len_2, len_3, len_4)

10 27 110 6 848


In [7]:

lesn_li = [len_0,len_1,len_2,len_3,len_4]
lis_arr = np.array(lesn_li)

print(np.min(lis_arr))
print(np.argwhere(lis_arr==6))

6
[[3]]


In [8]:
#minority_race = np.argwhere(lis_arr==6)
minority_race = 3
print(minority_race)

3


#step 5


In [9]:
senior_citizens = age[age>60]
working_hour = new_data[:,6]
working_hours_sum = np.sum(working_hour[age>60])
senior_citizens_len = len(senior_citizens)
avg_working_hours =  working_hours_sum /senior_citizens_len
print("Avg Working hours:",avg_working_hours)

Avg Working hours: 31.42622950819672


#Step 6


In [10]:
education_num = new_data[:,1]


high = education_num[education_num > 10]

low = education_num[education_num <= 10]

income_column = new_data[:,7]
avg_pay_high = np.mean(high)
avg_pay_low = np.mean(low)
print(avg_pay_high,"\n",avg_pay_low)


12.954128440366972 
 8.689910979228486
